apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluent-demo-k8s
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: fluent-demo-k8s
    spec:
      containers:
      - name: fluent-demo-k8s
        imagePullPolicy: Always
        image: fluent-demo-k8s-image
        ports:
        - containerPort: 8080